from RazorModelClean import getYawDLQRRazornoactuator
from numpy import *

class generateDLQRvalsYawnoactuator:
    def __init__(self,dT=0.005):
        self.dT = dT
    def update(self):
        vels = arange(1,7,0.5)
        for k in range(0,len(vels)):
            sys,Klqr = getYawDLQRRazornoactuator(vels[k],0.01,self.dT)

            allGains = ravel(Klqr)

            if(k==0):
                gainmtx = hstack((vels[k],allGains))
            else:
                gainmtx = vstack((gainmtx,hstack((vels[k],allGains))))
        #print(gainmtx)
        savetxt('razorGains_dlqr_yaw_noactuator.txt',gainmtx,comments='# generated by generateDLQRvalsYaw.py referencing RazorModel.py')

        return gainmtx
